project_name: bl

builds:
- main: ./cmd/bl/main.go
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  flags:
  - -mod=vendor
  - -v
  ldflags:
  - -X github.com/binarylane/bl-cli.Build={{ .ShortCommit }}
  - -X github.com/binarylane/bl-cli.Major={{ .Major }}
  - -X github.com/binarylane/bl-cli.Minor={{ .Minor }}
  - -X github.com/binarylane/bl-cli.Patch={{ .Patch }}
  - -X github.com/binarylane/bl-cli.Label=release
  goos:
  - windows
  - darwin
  - linux
  ignore:
  - goos: darwin
    goarch: 386

archives:
- name_template: "bl-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
  files: [a-workaround-to-include-only-the-binary*]
  wrap_in_directory: false

checksum:
  name_template: "bl-cli-{{ .Version }}-checksums.sha256"

release:
  github:
    owner: binarylane
    name: bl-cli

changelog:
  skip: true
