name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Format
      run: if [ "$(gofmt -s -l ./cmd ./commands ./bl ./integration ./pkg | wc -l)" -gt 0 ]; then exit 1; fi
    
    - name: Build
      run: ./scripts/_build.sh

    - name: Unit Test
      run: go test -mod=vendor ./commands/... ./bl/... ./pkg/... .